/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.11u-20020201-2200
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    inline SwigValueWrapper() : tt(0) { }
    inline ~SwigValueWrapper() { if (tt) delete tt; } 
    inline SwigValueWrapper& operator=(T t) {tt = new T(t); return *this;}
    inline operator T() const {return *tt;}
    inline T *operator&() { return tt; }
};                                                    
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif



#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGEXPORT(void) SWIG_TypeClientData(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif




/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
SWIGEXPORT(PyObject *)        SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own) {
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyInstanceObject *inst;
    inst = PyObject_NEW(PyInstanceObject, &PyInstance_Type);
    if (!inst) return robj;
    inst->in_dict = PyDict_New();
    inst->in_class = (PyClassObject *) type->clientdata;
    Py_INCREF(inst->in_class);
    PyObject_SetAttrString((PyObject *)inst,(char*)"this",robj);
    Py_DECREF(robj);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString((PyObject *)inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = (PyObject *) inst;
    Py_INCREF(robj);
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_IDiaPresentation swig_types[0] 
#define  SWIGTYPE_p_IDiaOutputWindow swig_types[1] 
#define  SWIGTYPE_p_IColor swig_types[2] 
#define  SWIGTYPE_p_IHsv swig_types[3] 
#define  SWIGTYPE_p_IDia swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= mindiapyc.so
  ------------------------------------------------*/
#define SWIG_init    initmindiapyc

#define SWIG_name    "mindiapyc"

#include "iscript.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_IColor(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_IColor")) return NULL;
    result = (IColor *)new IColor();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IColor, 1);
    return resultobj;
}


static PyObject *_wrap_IColor_iRed_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IColor_iRed_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    if (arg1) arg1->iRed = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IColor_iRed_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IColor_iRed_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    result = (int ) (arg1->iRed);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IColor_iGreen_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IColor_iGreen_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    if (arg1) arg1->iGreen = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IColor_iGreen_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IColor_iGreen_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    result = (int ) (arg1->iGreen);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IColor_iBlue_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IColor_iBlue_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    if (arg1) arg1->iBlue = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IColor_iBlue_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IColor_iBlue_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    result = (int ) (arg1->iBlue);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_delete_IColor(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_IColor",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * IColor_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_IColor, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_IHsv(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_IHsv")) return NULL;
    result = (IHsv *)new IHsv();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IHsv, 1);
    return resultobj;
}


static PyObject *_wrap_IHsv_iHue_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IHsv_iHue_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    if (arg1) arg1->iHue = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IHsv_iHue_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IHsv_iHue_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    result = (int ) (arg1->iHue);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IHsv_iSaturation_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IHsv_iSaturation_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    if (arg1) arg1->iSaturation = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IHsv_iSaturation_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IHsv_iSaturation_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    result = (int ) (arg1->iSaturation);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IHsv_iValue_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IHsv_iValue_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    if (arg1) arg1->iValue = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IHsv_iValue_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IHsv_iValue_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    result = (int ) (arg1->iValue);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_delete_IHsv(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_IHsv",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * IHsv_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_IHsv, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_delete_IDiaOutputWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_IDiaOutputWindow",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_IsValid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_IsValid",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )((IDiaOutputWindow const *)arg1)->IsValid();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_Show(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_Show",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->Show();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_Hide(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_Hide",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->Hide();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_Maximize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_Maximize",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->Maximize();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_Restore(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_Restore",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->Restore();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetWidth(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_GetWidth",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetWidth();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetHeight(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_GetHeight",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetHeight();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetSize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oii:IDiaOutputWindow_SetSize",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->SetSize(arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetPos(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oii:IDiaOutputWindow_SetPos",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->SetPos(arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetDrawWidth(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_GetDrawWidth",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetDrawWidth();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetDrawHeight(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_GetDrawHeight",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetDrawHeight();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_Clear(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_Clear",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->Clear();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetColor(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiii:IDiaOutputWindow_SetColor",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->SetColor(arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetFont(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDiaOutputWindow_SetFont",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->SetFont((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetFontSize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    bool arg3 = false ;
    bool arg4 = false ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi|OO:IDiaOutputWindow_SetFontSize",&obj0,&arg2,&obj2,&obj3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    if (obj2)
    arg3 = (bool) PyInt_AsLong(obj2);
    if (PyErr_Occurred()) return NULL;
    if (obj3)
    arg4 = (bool) PyInt_AsLong(obj3);
    if (PyErr_Occurred()) return NULL;
    result = (bool )(arg1)->SetFontSize(arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetTextXY(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    char *arg4 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiis:IDiaOutputWindow_SetTextXY",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )(arg1)->SetTextXY(arg2,arg3,(char const *)arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextCount(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaOutputWindow_GetTextCount",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetTextCount();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_MoveText(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiii:IDiaOutputWindow_MoveText",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->MoveText(arg2,arg3,arg4);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextX(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_GetTextX",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetTextX(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextY(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_GetTextY",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetTextY(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextWidth(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_GetTextWidth",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetTextWidth(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextHeight(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_GetTextHeight",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (int )((IDiaOutputWindow const *)arg1)->GetTextHeight(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_SetTextColor(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    int arg5 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oiiii:IDiaOutputWindow_SetTextColor",&obj0,&arg2,&arg3,&arg4,&arg5)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->SetTextColor(arg2,arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_GetTextColor(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    IColor result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_GetTextColor",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = ((IDiaOutputWindow const *)arg1)->GetTextColor(arg2);
    
    {
        IColor * resultptr;
        resultptr = new IColor (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_IColor, 1);
    }
    return resultobj;
}


static PyObject *_wrap_IDiaOutputWindow_DeleteText(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaOutputWindow *arg1 ;
    int arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaOutputWindow_DeleteText",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaOutputWindow,1)) == -1) return NULL;
    result = (bool )(arg1)->DeleteText(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject * IDiaOutputWindow_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_IDiaOutputWindow, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_delete_IDia(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_IDia",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IDia_GetTotalTime(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetTotalTime",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (double )((IDia const *)arg1)->GetTotalTime();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetShowTime(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetShowTime",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (double )((IDia const *)arg1)->GetShowTime();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_IDia_SetShowTime(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    double arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:IDia_SetShowTime",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetShowTime(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetDissolveTime(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetDissolveTime",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (double )((IDia const *)arg1)->GetDissolveTime();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_IDia_SetDissolveTime(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    double arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Od:IDia_SetDissolveTime",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetDissolveTime(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetId(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetId",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (char *)((IDia const *)arg1)->GetId();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDia_SetId(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDia_SetId",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetId((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetComment(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetComment",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (char *)((IDia const *)arg1)->GetComment();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDia_SetComment(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDia_SetComment",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetComment((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetImageFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetImageFile",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (char *)((IDia const *)arg1)->GetImageFile();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDia_SetImageFile(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDia_SetImageFile",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetImageFile((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetScript(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetScript",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (char *)((IDia const *)arg1)->GetScript();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDia_SetScript(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDia_SetScript",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )(arg1)->SetScript((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_GetHorizontalFormat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDia_GetHorizontalFormat",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    result = (bool )((IDia const *)arg1)->GetHorizontalFormat();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDia_SetHorizontalFormat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDia *arg1 ;
    bool arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:IDia_SetHorizontalFormat",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDia,1)) == -1) return NULL;
    arg2 = (bool) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) return NULL;
    result = (bool )(arg1)->SetHorizontalFormat(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject * IDia_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_IDia, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_delete_IDiaPresentation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_IDiaPresentation",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_IsChanged(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_IsChanged",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )((IDiaPresentation const *)arg1)->IsChanged();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetDocName(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetDocName",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (char *)((IDiaPresentation const *)arg1)->GetDocName();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetDescription(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetDescription",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (char *)((IDiaPresentation const *)arg1)->GetDescription();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetDiaCount(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetDiaCount",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (int )((IDiaPresentation const *)arg1)->GetDiaCount();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetDia(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int arg2 ;
    IDia *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaPresentation_GetDia",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (IDia *)(arg1)->GetDia(arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IDia, 0);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_AddNewDia(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    IDia *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_AddNewDia",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (IDia *)(arg1)->AddNewDia();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IDia, 0);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetSoundFileCount(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetSoundFileCount",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (int )((IDiaPresentation const *)arg1)->GetSoundFileCount();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetSoundFileNameAt(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int arg2 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaPresentation_GetSoundFileNameAt",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (char *)((IDiaPresentation const *)arg1)->GetSoundFileNameAt(arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_SetSoundFileNameAt(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int arg2 ;
    char *arg3 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Ois:IDiaPresentation_SetSoundFileNameAt",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->SetSoundFileNameAt(arg2,(char const *)arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetOutputWindow(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    IDiaOutputWindow *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetOutputWindow",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (IDiaOutputWindow *)(arg1)->GetOutputWindow();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IDiaOutputWindow, 0);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_LoadPresentation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    char *arg2 ;
    bool arg3 = true ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os|O:IDiaPresentation_LoadPresentation",&obj0,&arg2,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    if (obj2)
    arg3 = (bool) PyInt_AsLong(obj2);
    if (PyErr_Occurred()) return NULL;
    result = (bool )(arg1)->LoadPresentation((char const *)arg2,arg3);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_SavePresentation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_SavePresentation",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->SavePresentation();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_SavePresentationAs(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    char *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:IDiaPresentation_SavePresentationAs",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->SavePresentationAs((char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GotoPosition(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaPresentation_GotoPosition",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->GotoPosition(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_PlayFrom(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    int arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:IDiaPresentation_PlayFrom",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->PlayFrom(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_Play(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_Play",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->Play();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_Stop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_Stop",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->Stop();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_Pause(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_Pause",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->Pause();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_Continue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_Continue",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )(arg1)->Continue();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_IsPlayModus(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_IsPlayModus",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )((IDiaPresentation const *)arg1)->IsPlayModus();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_IsPauseModus(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_IsPauseModus",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )((IDiaPresentation const *)arg1)->IsPauseModus();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_IsEditModus(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_IsEditModus",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )((IDiaPresentation const *)arg1)->IsEditModus();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_GetPlayModusStrg(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    char *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_GetPlayModusStrg",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (char *)((IDiaPresentation const *)arg1)->GetPlayModusStrg();
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_IsSimulation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:IDiaPresentation_IsSimulation",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    result = (bool )((IDiaPresentation const *)arg1)->IsSimulation();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_IDiaPresentation_SetSimulation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *arg1 ;
    bool arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:IDiaPresentation_SetSimulation",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IDiaPresentation,1)) == -1) return NULL;
    arg2 = (bool) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) return NULL;
    (arg1)->SetSimulation(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * IDiaPresentation_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_IDiaPresentation, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_GetDiaPresentation(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IDiaPresentation *result;
    
    if(!PyArg_ParseTuple(args,(char *)":GetDiaPresentation")) return NULL;
    result = (IDiaPresentation *)GetDiaPresentation();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_IDiaPresentation, 0);
    return resultobj;
}


static PyObject *_wrap_PrintLn(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    
    if(!PyArg_ParseTuple(args,(char *)"s:PrintLn",&arg1)) return NULL;
    PrintLn((char const *)arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_DoMessageBox(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)"ss:DoMessageBox",&arg1,&arg2)) return NULL;
    result = (int )DoMessageBox((char const *)arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_SleepMS(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    
    if(!PyArg_ParseTuple(args,(char *)"i:SleepMS",&arg1)) return NULL;
    SleepMS(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_RgbToHsv(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IColor *arg1 ;
    IHsv result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:RgbToHsv",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IColor,1)) == -1) return NULL;
    result = RgbToHsv((IColor const &)*arg1);
    
    {
        IHsv * resultptr;
        resultptr = new IHsv (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_IHsv, 1);
    }
    return resultobj;
}


static PyObject *_wrap_HsvToRgb(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    IHsv *arg1 ;
    IColor result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:HsvToRgb",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_IHsv,1)) == -1) return NULL;
    result = HsvToRgb((IHsv const &)*arg1);
    
    {
        IColor * resultptr;
        resultptr = new IColor (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_IColor, 1);
    }
    return resultobj;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"new_IColor", _wrap_new_IColor, METH_VARARGS },
	 { (char *)"IColor_iRed_set", _wrap_IColor_iRed_set, METH_VARARGS },
	 { (char *)"IColor_iRed_get", _wrap_IColor_iRed_get, METH_VARARGS },
	 { (char *)"IColor_iGreen_set", _wrap_IColor_iGreen_set, METH_VARARGS },
	 { (char *)"IColor_iGreen_get", _wrap_IColor_iGreen_get, METH_VARARGS },
	 { (char *)"IColor_iBlue_set", _wrap_IColor_iBlue_set, METH_VARARGS },
	 { (char *)"IColor_iBlue_get", _wrap_IColor_iBlue_get, METH_VARARGS },
	 { (char *)"delete_IColor", _wrap_delete_IColor, METH_VARARGS },
	 { (char *)"IColor_swigregister", IColor_swigregister, METH_VARARGS },
	 { (char *)"new_IHsv", _wrap_new_IHsv, METH_VARARGS },
	 { (char *)"IHsv_iHue_set", _wrap_IHsv_iHue_set, METH_VARARGS },
	 { (char *)"IHsv_iHue_get", _wrap_IHsv_iHue_get, METH_VARARGS },
	 { (char *)"IHsv_iSaturation_set", _wrap_IHsv_iSaturation_set, METH_VARARGS },
	 { (char *)"IHsv_iSaturation_get", _wrap_IHsv_iSaturation_get, METH_VARARGS },
	 { (char *)"IHsv_iValue_set", _wrap_IHsv_iValue_set, METH_VARARGS },
	 { (char *)"IHsv_iValue_get", _wrap_IHsv_iValue_get, METH_VARARGS },
	 { (char *)"delete_IHsv", _wrap_delete_IHsv, METH_VARARGS },
	 { (char *)"IHsv_swigregister", IHsv_swigregister, METH_VARARGS },
	 { (char *)"delete_IDiaOutputWindow", _wrap_delete_IDiaOutputWindow, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_IsValid", _wrap_IDiaOutputWindow_IsValid, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_Show", _wrap_IDiaOutputWindow_Show, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_Hide", _wrap_IDiaOutputWindow_Hide, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_Maximize", _wrap_IDiaOutputWindow_Maximize, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_Restore", _wrap_IDiaOutputWindow_Restore, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetWidth", _wrap_IDiaOutputWindow_GetWidth, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetHeight", _wrap_IDiaOutputWindow_GetHeight, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetSize", _wrap_IDiaOutputWindow_SetSize, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetPos", _wrap_IDiaOutputWindow_SetPos, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetDrawWidth", _wrap_IDiaOutputWindow_GetDrawWidth, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetDrawHeight", _wrap_IDiaOutputWindow_GetDrawHeight, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_Clear", _wrap_IDiaOutputWindow_Clear, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetColor", _wrap_IDiaOutputWindow_SetColor, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetFont", _wrap_IDiaOutputWindow_SetFont, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetFontSize", _wrap_IDiaOutputWindow_SetFontSize, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetTextXY", _wrap_IDiaOutputWindow_SetTextXY, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextCount", _wrap_IDiaOutputWindow_GetTextCount, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_MoveText", _wrap_IDiaOutputWindow_MoveText, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextX", _wrap_IDiaOutputWindow_GetTextX, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextY", _wrap_IDiaOutputWindow_GetTextY, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextWidth", _wrap_IDiaOutputWindow_GetTextWidth, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextHeight", _wrap_IDiaOutputWindow_GetTextHeight, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_SetTextColor", _wrap_IDiaOutputWindow_SetTextColor, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_GetTextColor", _wrap_IDiaOutputWindow_GetTextColor, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_DeleteText", _wrap_IDiaOutputWindow_DeleteText, METH_VARARGS },
	 { (char *)"IDiaOutputWindow_swigregister", IDiaOutputWindow_swigregister, METH_VARARGS },
	 { (char *)"delete_IDia", _wrap_delete_IDia, METH_VARARGS },
	 { (char *)"IDia_GetTotalTime", _wrap_IDia_GetTotalTime, METH_VARARGS },
	 { (char *)"IDia_GetShowTime", _wrap_IDia_GetShowTime, METH_VARARGS },
	 { (char *)"IDia_SetShowTime", _wrap_IDia_SetShowTime, METH_VARARGS },
	 { (char *)"IDia_GetDissolveTime", _wrap_IDia_GetDissolveTime, METH_VARARGS },
	 { (char *)"IDia_SetDissolveTime", _wrap_IDia_SetDissolveTime, METH_VARARGS },
	 { (char *)"IDia_GetId", _wrap_IDia_GetId, METH_VARARGS },
	 { (char *)"IDia_SetId", _wrap_IDia_SetId, METH_VARARGS },
	 { (char *)"IDia_GetComment", _wrap_IDia_GetComment, METH_VARARGS },
	 { (char *)"IDia_SetComment", _wrap_IDia_SetComment, METH_VARARGS },
	 { (char *)"IDia_GetImageFile", _wrap_IDia_GetImageFile, METH_VARARGS },
	 { (char *)"IDia_SetImageFile", _wrap_IDia_SetImageFile, METH_VARARGS },
	 { (char *)"IDia_GetScript", _wrap_IDia_GetScript, METH_VARARGS },
	 { (char *)"IDia_SetScript", _wrap_IDia_SetScript, METH_VARARGS },
	 { (char *)"IDia_GetHorizontalFormat", _wrap_IDia_GetHorizontalFormat, METH_VARARGS },
	 { (char *)"IDia_SetHorizontalFormat", _wrap_IDia_SetHorizontalFormat, METH_VARARGS },
	 { (char *)"IDia_swigregister", IDia_swigregister, METH_VARARGS },
	 { (char *)"delete_IDiaPresentation", _wrap_delete_IDiaPresentation, METH_VARARGS },
	 { (char *)"IDiaPresentation_IsChanged", _wrap_IDiaPresentation_IsChanged, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetDocName", _wrap_IDiaPresentation_GetDocName, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetDescription", _wrap_IDiaPresentation_GetDescription, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetDiaCount", _wrap_IDiaPresentation_GetDiaCount, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetDia", _wrap_IDiaPresentation_GetDia, METH_VARARGS },
	 { (char *)"IDiaPresentation_AddNewDia", _wrap_IDiaPresentation_AddNewDia, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetSoundFileCount", _wrap_IDiaPresentation_GetSoundFileCount, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetSoundFileNameAt", _wrap_IDiaPresentation_GetSoundFileNameAt, METH_VARARGS },
	 { (char *)"IDiaPresentation_SetSoundFileNameAt", _wrap_IDiaPresentation_SetSoundFileNameAt, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetOutputWindow", _wrap_IDiaPresentation_GetOutputWindow, METH_VARARGS },
	 { (char *)"IDiaPresentation_LoadPresentation", _wrap_IDiaPresentation_LoadPresentation, METH_VARARGS },
	 { (char *)"IDiaPresentation_SavePresentation", _wrap_IDiaPresentation_SavePresentation, METH_VARARGS },
	 { (char *)"IDiaPresentation_SavePresentationAs", _wrap_IDiaPresentation_SavePresentationAs, METH_VARARGS },
	 { (char *)"IDiaPresentation_GotoPosition", _wrap_IDiaPresentation_GotoPosition, METH_VARARGS },
	 { (char *)"IDiaPresentation_PlayFrom", _wrap_IDiaPresentation_PlayFrom, METH_VARARGS },
	 { (char *)"IDiaPresentation_Play", _wrap_IDiaPresentation_Play, METH_VARARGS },
	 { (char *)"IDiaPresentation_Stop", _wrap_IDiaPresentation_Stop, METH_VARARGS },
	 { (char *)"IDiaPresentation_Pause", _wrap_IDiaPresentation_Pause, METH_VARARGS },
	 { (char *)"IDiaPresentation_Continue", _wrap_IDiaPresentation_Continue, METH_VARARGS },
	 { (char *)"IDiaPresentation_IsPlayModus", _wrap_IDiaPresentation_IsPlayModus, METH_VARARGS },
	 { (char *)"IDiaPresentation_IsPauseModus", _wrap_IDiaPresentation_IsPauseModus, METH_VARARGS },
	 { (char *)"IDiaPresentation_IsEditModus", _wrap_IDiaPresentation_IsEditModus, METH_VARARGS },
	 { (char *)"IDiaPresentation_GetPlayModusStrg", _wrap_IDiaPresentation_GetPlayModusStrg, METH_VARARGS },
	 { (char *)"IDiaPresentation_IsSimulation", _wrap_IDiaPresentation_IsSimulation, METH_VARARGS },
	 { (char *)"IDiaPresentation_SetSimulation", _wrap_IDiaPresentation_SetSimulation, METH_VARARGS },
	 { (char *)"IDiaPresentation_swigregister", IDiaPresentation_swigregister, METH_VARARGS },
	 { (char *)"GetDiaPresentation", _wrap_GetDiaPresentation, METH_VARARGS },
	 { (char *)"PrintLn", _wrap_PrintLn, METH_VARARGS },
	 { (char *)"DoMessageBox", _wrap_DoMessageBox, METH_VARARGS },
	 { (char *)"SleepMS", _wrap_SleepMS, METH_VARARGS },
	 { (char *)"RgbToHsv", _wrap_RgbToHsv, METH_VARARGS },
	 { (char *)"HsvToRgb", _wrap_HsvToRgb, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_IDiaPresentation[] = {{"_p_IDiaPresentation", 0, "IDiaPresentation *"},{"_p_IDiaPresentation"},{0}};
static swig_type_info _swigt__p_IDiaOutputWindow[] = {{"_p_IDiaOutputWindow", 0, "IDiaOutputWindow *"},{"_p_IDiaOutputWindow"},{0}};
static swig_type_info _swigt__p_IColor[] = {{"_p_IColor", 0, "IColor *"},{"_p_IColor"},{0}};
static swig_type_info _swigt__p_IHsv[] = {{"_p_IHsv", 0, "IHsv *"},{"_p_IHsv"},{0}};
static swig_type_info _swigt__p_IDia[] = {{"_p_IDia", 0, "IDia *"},{"_p_IDia"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_IDiaPresentation, 
_swigt__p_IDiaOutputWindow, 
_swigt__p_IColor, 
_swigt__p_IHsv, 
_swigt__p_IDia, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

